# Generated by Django 5.0.1 on 2024-01-09 05:09

import payrollapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0027_alter_step1sub3_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step1sub3',
            name='pincode',
            field=models.CharField(default='', max_length=10, validators=[payrollapp.models.validate_pincode]),
        ),
    ]
